### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by ingve** [larshagencpp/larshagencpp.github.io#1]
Feedwrangler is unable to find an RSS feed for larshagencpp.github.io (Error message: "No RSS Feed Found"), and a manual inspection of the HTML source does not reveal any RSS-/Atom-feed-related links.

**Comment by larshagencpp** [comment]
Thanks for pointing it out, I will push a fix for this tonight.

**Comment by larshagencpp** [comment]
Should be fixed now. I really appreciate you taking the time to notify me of this.
